from __future__ import annotations

from typing import Dict, List, Optional, Any
from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    timestamp: Any  # datetime
    action: str     # "buy", "sell", "close"
    price: float
    size: float = 1.0
    metadata: Optional[Dict] = None


@dataclass
class Bar:
    """Normalized price bar for strategy consumption."""
    timestamp: Any
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0


class Strategy(ABC):
    """Base class for all trading strategies."""

    name: str = "base"
    description: str = ""

    def __init__(self, params: Optional[Dict[str, Any]] = None):
        self.params = params or {}
        self._position: Optional[str] = None  # "long", "short", None
        self._bars: List[Bar] = []

    @abstractmethod
    def on_bar(self, bar: Bar) -> Optional[Signal]:
        """Called on each new bar. Return a Signal or None."""
        ...

    def reset(self):
        """Reset strategy state for a new backtest run."""
        self._position = None
        self._bars = []

    @property
    def params_schema(self) -> Dict[str, Any]:
        """Override in subclass to define tunable parameters."""
        return {}
